# Generated by Django 4.2.16 on 2025-01-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ailogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("imgpath", models.CharField(default=None, max_length=255, null=True)),
                ("aitype", models.SmallIntegerField(default=1)),
                ("result", models.TextField(default=None, null=True)),
                ("dtime", models.DateTimeField(auto_now_add=True)),
                ("delta_time", models.FloatField(default=None, null=True)),
                ("userid", models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
