# Generated by Django 5.1.4 on 2025-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ailogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("imgpath", models.CharField(default=None, max_length=255, null=True)),
                ("aitype", models.SmallIntegerField(default=1)),
                ("result", models.TextField(default=None, null=True)),
                ("dtime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
