# Generated by Django 5.1.4 on 2025-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_drone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailogs",
            name="delta_time",
            field=models.FloatField(default=None, null=True),
        ),
    ]
