# Generated by Django 5.1.4 on 2025-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_drone", "0002_ailogs_delta_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailogs",
            name="userid",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
